# Generated by Django 5.0.3 on 2026-03-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Travel', 'Travel'), ('Fuel', 'Fuel'), ('Repair', 'Repair'), ('Courier', 'Courier'), ('Other', 'Other')], default='Other', max_length=50)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('bill_due_date', models.DateField(blank=True, null=True)),
                ('file_path', models.FileField(upload_to='bills/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Under Review', 'Under Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
