# Generated by Django 5.0.3 on 2026-03-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='ocr_extracted_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='category',
            field=models.CharField(
                choices=[
                    ('Travel', 'Travel'),
                    ('Fuel', 'Fuel'),
                    ('Repair', 'Repair'),
                    ('Courier', 'Courier'),
                    ('Office Supplies', 'Office Supplies'),
                    ('Other', 'Other')
                ],
                default='Other',
                max_length=50
            ),
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(
                choices=[
                    ('UPLOADED', 'UPLOADED'),
                    ('ACCOUNTANT_VERIFIED', 'ACCOUNTANT_VERIFIED'),
                    ('MANAGER_APPROVED', 'MANAGER_APPROVED'),
                    ('MANAGER_REJECTED', 'MANAGER_REJECTED'),
                    ('CEO_APPROVED', 'CEO_APPROVED'),
                    ('CEO_REJECTED', 'CEO_REJECTED'),
                    ('PAID', 'PAID')
                ],
                default='UPLOADED',
                max_length=50
            ),
        ),
        migrations.AlterField(
            model_name='bill',
            name='vendor_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
