# Generated by Django 5.0.3 on 2026-03-06 00:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bills', '0003_bill_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='bills/'),
        ),
    ]
