# Generated by Django 5.0.3 on 2026-03-06 01:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bills', '0004_bill_file_path_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(
                choices=[
                    ('UPLOADED', 'UPLOADED'),
                    ('ACCOUNTANT_VERIFIED', 'ACCOUNTANT_VERIFIED'),
                    ('MANAGER_APPROVED', 'MANAGER_APPROVED'),
                    ('MANAGER_REJECTED', 'MANAGER_REJECTED'),
                    ('CEO_APPROVED', 'CEO_APPROVED'),
                    ('CEO_REJECTED', 'CEO_REJECTED'),
                    ('UNDER_REVIEW', 'UNDER_REVIEW'),
                    ('APPROVED', 'APPROVED'),
                    ('REJECTED', 'REJECTED'),
                    ('PAID', 'PAID')
                ],
                default='UPLOADED',
                max_length=50,
            ),
        ),
    ]
