# Generated by Django 5.0.3 on 2026-03-06 01:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bills', '0005_bill_status_under_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='overdue_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
