# Generated by Django 5.0.3 on 2026-03-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='approver_role',
            field=models.CharField(
                choices=[('ACCOUNTANT', 'ACCOUNTANT'), ('MANAGER', 'MANAGER'), ('CEO', 'CEO')],
                max_length=50
            ),
        ),
        migrations.AlterField(
            model_name='approval',
            name='status',
            field=models.CharField(
                choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')],
                default='Pending',
                max_length=50
            ),
        ),
    ]
