# Generated by Django 5.0.3 on 2026-03-06 01:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('approvals', '0002_update_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='is_required',
            field=models.BooleanField(default=True),
        ),
    ]
